import type { LegendConfig } from "./types";

export const legendConfig: Record<string, LegendConfig> = {
  ndvi: {
    type: "gradient",
    title: "NDVI 植被覆盖",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #dadfaa, #578233)",
    notes: ["浅色表示低植被覆盖", "深绿色表示高植被覆盖"],
  },
  evi: {
    type: "gradient",
    title: "EVI 植被活力",
    low: "弱",
    high: "强",
    gradient: "linear-gradient(90deg, #d6dda9, #24845b)",
    notes: ["浅色表示植被活力较弱", "深绿色表示植被活力较强"],
  },
  ntl: {
    type: "gradient",
    title: "夜间灯光强度",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #2f3835, #e7b133)",
    notes: ["暗色表示人类活动较弱", "黄色表示灯光和建设活动更强"],
  },
  gdp: {
    type: "gradient",
    title: "GDP 空间强度",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #59452e, #d6914b)",
    notes: ["深褐表示经济强度较低", "橙色表示经济强度较高"],
  },
  ri: {
    type: "gradient",
    title: "生态韧性指数 RI",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #ae4134, #d6b650, #4a8e4f)",
    notes: ["红色表示相对低韧性区域", "绿色表示相对高韧性区域"],
  },
  four_dim_er: {
    type: "gradient",
    title: "四维综合生态韧性 ER",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #a83730, #e2be56, #368458)",
    notes: ["红色表示综合韧性较低", "绿色表示综合韧性较强"],
  },
  four_dim_ers: {
    type: "gradient",
    title: "规模韧性 ERS",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #bc503b, #dcbf5c, #408b50)",
    notes: ["值越高表示生态基础设施规模韧性越强"],
  },
  four_dim_erd: {
    type: "gradient",
    title: "密度韧性 ERD",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #ae4737, #dbb655, #3f7f67)",
    notes: ["值越高表示生态承载相对人类活动压力更强"],
  },
  four_dim_erm: {
    type: "gradient",
    title: "形态韧性 ERM",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #96494a, #d2b263, #367f74)",
    notes: ["值越高表示更接近生态斑块或生态汇"],
  },
  four_dim_erf: {
    type: "gradient",
    title: "洪水韧性 ERF",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #a23d3a, #d8b860, #337e8b)",
    notes: ["值越高表示洪水韧性越强"],
  },
  four_dim_fri: {
    type: "gradient",
    title: "洪水风险 FRI",
    low: "低",
    high: "高",
    gradient: "linear-gradient(90deg, #316b97, #e7be63, #b63730)",
    notes: ["值越高表示洪水风险越高"],
  },
  clcd: {
    type: "categories",
    title: "CLCD 土地利用",
    items: [
      ["#d3b869", "耕地"],
      ["#387d4c", "林地"],
      ["#739750", "灌木"],
      ["#97b863", "草地"],
      ["#35849e", "水体"],
      ["#c4b58b", "裸地/未利用地"],
      ["#b75236", "建设用地"],
    ],
  },
  water: {
    type: "categories",
    title: "JRC 水体分类",
    items: [
      ["#92c5d6", "季节性水体"],
      ["#268bb0", "常年水体"],
      ["#0c5386", "高频稳定水体"],
    ],
  },
};
